### ISSUE TITLE
Command line executable panicks when using ndk-glue / NativeActivity Code

### ISSUE THREAD

**Issue by szsoftware** [rust-windowing/android-ndk-rs#126]
Hi there,
following scenario:
An executable compiled with android/termux framework/toolchain panicks with code that points to some Activity logic.

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/builder/.cargo/registry/src/github.com-1ecc6299db9ec823/ndk-glue-0.2.1/src/lib.rs:42:39

Of course there is a NPE since there is no gui application, respectively Activity/Looper involved (the executable is called from adb-shell or via System.exec("myRustExecutable someInput") ).

So several questions: How can I compile the whole thing to hunt down the error, so I can patch that call out?
How can I otherwise omit/circumvent this piece of gui code?

If I only had a full stacktrace, I would look into the calling code, but I have no idea when the ndk calls ndk-glue.
Due to this massive crosscompiling toolchain involved I have no clue how to debug anything.

Thanks for your help!

**Comment by MarijnS95** [comment]
> Of course there is a NPE since there is no gui application, respectively Activity/Looper involved (the executable is called from adb-shell or via System.exec("myRustExecutable someInput") ).

If you are not compiling an Android app - that is inherently forced to use `NativeActivity` - but a simple binary to be executed you don't need `android-ndk-rs` at all :tada: 

Just use `cargo build` to get a normal binary that can be executed, without any `ndk_glue::main` macro on `fn main`.

**Comment by MarijnS95** [comment]
For what it's worth, even without stacktrace this is relatively easy to debug. The error includes all necessary information: `src/lib.rs:42` in the `ndk-glue` crate on version 0.2.1:

https://github.com/rust-windowing/android-ndk-rs/blob/7d36455f8b850ce716debcef551f86fc7fa9ecaf/ndk-glue/src/lib.rs#L42

Which is only ever assigned once, when the native activity is set up:

https://github.com/rust-windowing/android-ndk-rs/blob/7d36455f8b850ce716debcef551f86fc7fa9ecaf/ndk-glue/src/lib.rs#L140

**Comment by MarijnS95** [comment]
@szsoftware Any extra context that we can use to help you resolve this issue? Inclined to close otherwise.

**Comment by szsoftware** [comment]
Hi there!

Thanks for the reminder. I will push my investigation on this issue on highest priority, since I'm urging for any developments regarding this issue/battlefield (tectonic on Android).

**Comment by MarijnS95** [comment]
Closing due to inactivity. Feel free to reopen if more information is available.

**Comment by Babber** [comment]
Dear All,
I have found this thread because I am trying to run `tectonic` in Termux and it also returns this error message:
```thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/builder/.cargo/registry/src/github.com-1ecc6299db9ec823/ndk-glue-0.3.0/src/lib.rs:54:39```
Is there any way to fix this? Is there any reasonable workaround?

**Comment by pkgw** [comment]
If anyone can get a full backtrace of the Tectonic crash that is causing this panic, I think that would still be helpful for solving the reported problem — although my impression is that it's unlikely to represent a bug in this repo. I don't know Android at all, but it sounds like maybe some aspect of Tectonic's dependency tree is turning on stuff that is expecting it to have GUI features, when it doesn't? I feel like maybe we need to add a `default-features = false` somewhere in our `Cargo.toml` files.

**Comment by MarijnS95** [comment]
@pkgw That observation is entirely correct. As replied in https://github.com/tectonic-typesetting/tectonic/issues/926#issuecomment-1243470977 this is most likely caused by a transitive dependency assuming an Android app - started through `ndk-glue` (and hopefully later `ndk-context`) - triggered by `cfg!(target_os = "android")` code which is how [Termux compiles their Rust code](https://github.com/termux/termux-packages/blob/4c7c879a7d550aadff3d0acc98bd757f033fb658/scripts/build/setup/termux_setup_rust.sh#L2-L6), despite having to function as if it's a "normal" desktop/commandline binary.

We'd have to come up with a more global/accepted solution for this, even though Termux appears to be one of the only/few bits of software that wouldn't want their code to be assuming / defaulting to Android App behaviour.
